---
title: "EMT_analyses"
author: "Angèle COUTANT"
date: "2023-07-04"
output: html_document
---

```{r, include=FALSE}
library(Seurat)       # Importation des données/Quantification
library(scater)       # Control Qualité
library(sctransform)  # Normalisation par seurat
library(biomaRt)      # Re Annotation des gènes
library(AUCell) 
#library(MAST)         # Analyse différentielle
library(pROC)
library(ggplot2)
library(GSEABase)
library(cowplot)
library(RColorBrewer)
library(data.table)
library(devtools)
# library(SCENT)
library(DescTools)
library(plyr)
library(reticulate)

source('/mnt/Commun/Single_cell/functions.R')
load("/mnt/Commun/Donnees/GOgenes_HGNC_ExtSymb.RData")

```

```{r}
rainbow_act = c('#339900', '#0066CC', "#E69F00", "#FFCC33", "#990033", "#CC0033")

pid <- 'EMT'
setwd(sprintf('/mnt/Commun/sc_Induction/%s/', pid))

color = rainbow_act[1]
activity = "HALLMARK_EPITHELIAL_MESENCHYMAL_TRANSITION"
GO = genesGO[["GO_EPITHELIAL_TO_MESENCHYMAL_TRANSITION"]]@geneIds
gmtFile <- "/mnt/Commun/sc_Induction/Donnees/h.all.v6.2.symbols.gmt"
geneSets <- getGmt(gmtFile)
HM <- geneSets[[activity]]@geneIds
mart <- useMart("ensembl", dataset="hsapiens_gene_ensembl", host = "https://dec2021.archive.ensembl.org")
HM_list <- getBM(attributes=c('external_synonym', 'hgnc_symbol'), filters= "external_synonym" ,values= HM, mart=mart, uniqueRows=T, useCache = FALSE)
HM_list2 <- getBM(attributes=c('external_synonym', 'hgnc_symbol'), filters= 'hgnc_symbol' ,values=HM, mart=mart, uniqueRows=T, useCache = FALSE)
HM_list <- rbind(HM_list2, HM_list)
HM <- unique(c(HM_list$external_synonym, HM_list$hgnc_symbol))
```

### QC and normalisation

```{r, echo = FALSE, include = FALSE}
sce_act <- Read10X(data.dir = sprintf('/mnt/Commun/sc_Induction/%s/Donnees/%s_filtered_feature_bc_matrix', pid, pid))
sce_inact <- Read10X(data.dir = sprintf('/mnt/Commun/sc_Induction/%s/Donnees/Control_filtered_feature_bc_matrix/',pid))
colnames(sce_act) = paste(colnames(sce_act), '_activ', sep = '')
colnames(sce_inact) = paste(colnames(sce_inact), '_inactiv', sep = '')

act_obj = CreateSeuratObject(sce_act, project = pid)
inact_obj = CreateSeuratObject(sce_inact, project = 'Control')

act_obj[["percent.mt"]] <- PercentageFeatureSet(act_obj, pattern = "^MT-")
inact_obj[["percent.mt"]] <- PercentageFeatureSet(inact_obj, pattern = "^MT-")
act_obj[["percent.rb"]] <- PercentageFeatureSet(act_obj, pattern = "^RP[SL]")
inact_obj[["percent.rb"]] <- PercentageFeatureSet(inact_obj, pattern = "^RP[SL]")

pdf('Filters.pdf')

VlnPlot(act_obj, features = c("nFeature_RNA","nCount_RNA","percent.mt","percent.rb"),ncol = 4, pt.size = 0.1) & 
   theme(plot.title = element_text(size=10))
VlnPlot(inact_obj, features = c("nFeature_RNA","nCount_RNA","percent.mt","percent.rb"),ncol = 4, pt.size = 0.1) & 
   theme(plot.title = element_text(size=10))

par(mfrow = c(3,1), mar = c(4, 4, 1, 3))

hist(act_obj$nCount_RNA, breaks = 50, xlab = '', main = '', col=rainbow_act[1]) 
abline(v=10000, col = 'red', lwd=2)
abline(v=80000, col='red', lwd=2)
plot(act_obj$percent.mt ~ act_obj$nCount_RNA, xlab = '', ylab = 'percent.mt', pch =16)
abline(h=20, col='red', lwd=2)
plot(act_obj$nFeature_RNA ~ act_obj$nCount_RNA, xlab = sprintf('nCount RNA',pid), ylab = 'n_features', pch =16)
abline(h=200, col='red', lwd=2)

hist(inact_obj$nCount_RNA, breaks = 50 , xlab = '', main ='', col='grey') 
abline(v=10000, col = 'red', lwd=2)
abline(v=80000, col='red', lwd=2)
plot(inact_obj$percent.mt ~ inact_obj$nCount_RNA, xlab = '', ylab = 'percent.mt', pch =16)
abline(h=20, col='red', lwd=2)
plot(inact_obj$nFeature_RNA ~ inact_obj$nCount_RNA, xlab = 'nCount RNA (Control)', ylab = 'n_features', pch =16)
abline(h=200, col='red', lwd=2)

dev.off()

nfeature = 200
mt_percent = 20
max_count = 80000
min_count = 10000

act_tokeep = which(act_obj$nFeature_RNA > nfeature & act_obj$percent.mt < mt_percent & act_obj$nCount_RNA < max_count & act_obj$nCount_RNA > min_count)
inact_tokeep = which(inact_obj$nFeature_RNA > nfeature & inact_obj$percent.mt < mt_percent & inact_obj$nCount_RNA < max_count & inact_obj$nCount_RNA > min_count)

Activ <- CreateSeuratObject(sce_act[,act_tokeep], project = pid, min.cells = 3)
Inactiv <- CreateSeuratObject(counts = sce_inact[,inact_tokeep], project = 'Control', min.cells = 3)

Activ = SCTransform(Activ)
Inactiv = SCTransform(Inactiv)

s.genes <- cc.genes$s.genes
g2m.genes <- cc.genes$g2m.genes
# 
s.gene = readRDS('/mnt/Commun/sc_Induction/Donnees/s.gene.Rds')
g2m.gene = readRDS('/mnt/Commun/sc_Induction/Donnees/g2m.gene.Rds')

cols_cycle <- c("S" = "orange", "G2M" = "darkolivegreen2", "G1" = "lightblue")

pdf('Cell_cycle_norm.pdf')
CC_act <- CellCycleScoring(object = Activ, s.features = s.gene, g2m.features = g2m.gene, set.ident = TRUE)
CC_inact <- CellCycleScoring(object = Inactiv, s.features = s.gene, g2m.features = g2m.gene, set.ident = TRUE)
CC_act.pca <- RunPCA(CC_act, features = c(s.genes, g2m.genes))
CC_inact.pca <- RunPCA(CC_inact, features = c(s.genes, g2m.genes))
DimPlot(CC_act.pca, cols = as.vector(cols_cycle)) + ggtitle(sprintf("Before Cell Cycle Norm (%s)", pid))
DimPlot(CC_inact.pca, cols = as.vector(cols_cycle)) + ggtitle("Before Cell Cycle Norm (Control)")

Activ <- SCTransform(CC_act, vars.to.regress = c("S.Score", "G2M.Score")) 
Inactiv <- SCTransform(CC_inact, vars.to.regress = c("S.Score", "G2M.Score"))
pca_act <- RunPCA(Activ, features = c(s.gene, g2m.gene))
pca_inact <- RunPCA(Inactiv, features = c(s.gene, g2m.gene))
DimPlot(pca_act, cols = as.vector(cols_cycle)) + ggtitle(sprintf("After Cell Cycle Norm (%s)", pid))
DimPlot(pca_inact, cols = as.vector(cols_cycle)) + ggtitle("After Cell Cycle Norm (Control)")

dev.off()

g = intersect(rownames(Activ), rownames(Inactiv))
both = cbind(Inactiv@assays[["SCT"]]@counts[g,], Activ@assays[["SCT"]]@counts[g,])

#Remove all zero after normalisation
both = both[-which(apply(both, 1, sum)==0),]
g = rownames(both)

isActiv <- rep(0:1, c(ncol(Inactiv), ncol(Activ)))
activStr <- as.factor(rep(c("inactive","active"), c(ncol(Inactiv), ncol(Activ))))

# filtered data for scvelo
Inact = as.matrix(Inactiv@assays[["SCT"]]@counts[g,])
colnames(Inact) = gsub('_inactiv', '_Control', colnames(Inact))
Act = as.matrix(Activ@assays[["SCT"]]@counts[g,])
colnames(Act) = gsub('_activ', sprintf('_%s', pid), colnames(Act))
# write.csv(Inact, 'Ctrl_filtered.csv')
# write.csv(Act, sprintf('%s_filtered.csv',pid))
```

```{python}
import matplotlib
import numpy as np
import pandas as pd
import scvelo as scv
import scanpy as sc
import csv
from scanpy import read
import cellrank as cr
from random import sample
import os

pid = 'EMT'

HM =[]
with open(f'/mnt/Commun/sc_Induction/{pid}/Donnees/HM_{pid}.csv') as HMcsv:
    EMTHM = csv.reader(HMcsv, delimiter=',', quotechar='"')
    for row in EMTHM:
        HM.append(''.join(row))
        
GO =[]
with open(f'/mnt/Commun/sc_Induction/{pid}/Donnees/GO_{pid}.csv') as GOcsv:
    EMTGO = csv.reader(GOcsv, delimiter=',', quotechar='"')
    for row in EMTGO:
        GO.append(''.join(row))
        

### From best gene Set for prediction        
EMT1 = []
with open(f'/mnt/Commun/sc_Induction/EMT_cinetique/Donnees/EMT1_Tirosh.csv') as EMT1csv:
    EMT1_T = csv.reader(EMT1csv, delimiter=',', quotechar='"')
    for row in EMT1_T:
        EMT1.append(''.join(row))
        
g = 'HM'
genes = HM

Ctrl = read(f'/mnt/Commun/sc_Induction/{pid}/Donnees/control.loom', sparse=True, cache=True)
Act = read(f'/mnt/Commun/sc_Induction/{pid}/Donnees/{pid}.loom', sparse=True, cache=True)

Ctrl = read(f'/mnt/Commun/sc_Induction/{pid}/Donnees/control.loom', sparse=True, cache=True)
Act = read(f'/mnt/Commun/sc_Induction/{pid}/Donnees/{pid}.loom', sparse=True, cache=True)

Ctrl.var_names_make_unique()
Act.var_names_make_unique()

cell_Ctrl = []
cell_Act = []

for i in Ctrl.obs_names :
    i = i.replace('Control_re:', '')
    i = i.replace('x', '-1_Control')
    cell_Ctrl.append(i)
    
for i in Act.obs_names :
    i = i.replace(f'{pid}_re:', '')
    i = i.replace('x', f'-1_{pid}')
    cell_Act.append(i)

    
Ctrl.obs_names = cell_Ctrl
Act.obs_names = cell_Act

### Importation des données filtrées
with open (f'/mnt/Commun/sc_Induction/{pid}/Donnees/Ctrl_filtered.csv', newline = '') as f_ctrl:
    ctrl_filter = csv.reader(f_ctrl)
    cell_ctrl_filter = next(ctrl_filter)[1:]
    
with open (f'/mnt/Commun/sc_Induction/{pid}/Donnees/{pid}_filtered.csv', newline = '') as f_Act:
    Act_filter = csv.reader(f_Act)
    cell_Act_filter = next(Act_filter)[1:]


cells_ctrl_filter = []
for i in cell_ctrl_filter:
    i=i.replace('.1_', '-1_')
    cells_ctrl_filter.append(i)
    
    
cells_Act_filter = []
for i in cell_Act_filter:
    i=i.replace('.1_', '-1_')
    cells_Act_filter.append(i)
    
Ctrl_filtered = Ctrl[Ctrl.obs_names.isin(cells_ctrl_filter), Ctrl.var_names.isin(genes)]
Act_filtered = Act[Act.obs_names.isin(cells_Act_filter), Act.var_names.isin(genes)]

#Import bootstraps

nboots = 20
Boots_Act_Ctrl = list(range(nboots))

for b in range(nboots):
    Row = []
    with open(f'/mnt/Commun/sc_Induction/{pid}/SCENT/Bootstraps/boot{b+1}_{pid}_Ctrl.csv') as Bootscsv:
        Boot = csv.reader(Bootscsv, delimiter=',', quotechar='"')
        next(Boot)
        for row in Boot:
            row = row[1]
            Row.append(''.join(row))
            Boots_Act_Ctrl[b] = Row
            
ntop = (50, 75, 100, 125, 150, 175, 200) 
shared = (25,50,75,100)

Boots = Boots_Act_Ctrl
id1 = "Control"
id2 = pid
col1 = "grey"
col2 = "#339900"
data1 = Ctrl_filtered
data2 = Act_filtered

### Fonction Pseudotemps 

def PseudoT(g, d1, d2, id1, id2, col1,col2):
    for b in range(nboots) :
        print("###########################################################")
        print("Bootstrap n°",b+1)
        print("ntop=", n)
        print("shared=", s)
        print("###########################################################")

        os.chdir(f'/mnt/Commun/sc_Induction/{pid}/SCENT/{g}/boot{b+1}/')
        os.getcwd()

        data_1 = d1[d1.obs_names.isin(Boots[b]),]
        data_2 = d2[d2.obs_names.isin(Boots[b]),]
        both = data_1.concatenate(data_2)

        D1D2 = []
        for i in both.obs_names :
            i = i.replace(f'{id1}-0', f'{id1}')
            i = i.replace(f'{id2}-1', f'{id2}')
            D1D2.append(i)
        both.obs_names = D1D2

        both.obs["induct"] = np.repeat([id1,id2], [data_1.shape[0], data_2.shape[0]], axis=0)
        scv.pp.filter_and_normalize(both, min_shared_counts=s, n_top_genes=n)

        data = both

        scv.pp.moments(data)
        scv.tl.umap(data, min_dist=1)
        scv.plotting.umap(data, color="induct",palette=(col1, col2), save=f"UMAP_{g}_{n}_{s}.pdf")

        scv.tl.velocity(data)
        scv.pp.neighbors(data)
        scv.tl.velocity_graph(data)
        scv.pl.velocity_embedding_stream(data , basis='umap', color='induct',palette=(col1, col2), save=f"Velocity_{g}_{n}_{s}.pdf")

        scv.tl.paga(data, groups='induct')
        scv.pl.paga(data, basis = "umap", palette=(col1, col2),  save = f"UMAP_paga_{g}_{n}_{s}.pdf")

        pseudo_time = scv.tl.velocity_pseudotime(data)
        scv.pl.scatter(data, color='velocity_pseudotime', color_map='gnuplot', save = f'Pseudotime_ntop{n}_shared{s}_{g}.pdf')
        Pseudotime_value = pd.DataFrame(data.obs['velocity_pseudotime'])
        Pseudotime_value.to_csv(f'Pseudotimes_{g}_{n}_{s}.csv')
```

### Test les parametres : pseudotemps/drivers 

```{python}
for n in ntop:
    for s in shared:
        PseudoT( g, data1, data2, id1, id2, col1, col2)
        
### Select best param per boot
Best_param_per_boot=[]
with open(f'/mnt/Commun/sc_Induction/{pid}/SCENT/{g}/Best_param_per_boot.csv') as Bootscsv:
    Boot = csv.reader(Bootscsv, delimiter=',', quotechar='"')
    next(Boot)
    for row in Boot:
        row = row[1]
        Best_param_per_boot.append(''.join(row))

os.chdir(f'/mnt/Commun/sc_Induction/{pid}/SCENT/{g}')
os.getcwd()

for b in range(len(Best_param_per_boot)) :

    print(b)
    n = int(Best_param_per_boot[b].split('_')[0])
    s = int(Best_param_per_boot[b].split('_')[1])

    both = data1.concatenate(data2)

    both.obs["induct"] = np.repeat([id1,id2], [data1.shape[0], data2.shape[0]], axis=0)

    scv.pp.filter_and_normalize(both, min_shared_counts=s, n_top_genes=n)

    data = both

    scv.pp.moments(data)
    scv.tl.umap(data, min_dist=1)
    scv.plotting.umap(data, color="induct",palette=(col1, col2), save=f"UMAP_{g}_{n}_{s}_boot{b}.png")

    scv.tl.velocity(data)
    scv.tl.velocity_graph(data)
    scv.pl.velocity_embedding_stream(data , basis='umap', color='induct',palette=(col1, col2), save=f"Velocity_{g}_{n}_{s}_boot{b}.png")

    cr.tl.initial_states(data , cluster_key="induct", n_states=1)
    cr.pl.initial_states(data , discrete=True, save=f"Initial_state_{g}_{n}_{s}_boot{b}.png")

    cr.tl.terminal_states(data , cluster_key="induct",  n_states=2,  weight_connectivities=0.2)
    cr.pl.terminal_states(data , discrete=True, save=f"Terminal_states_{g}_{n}_{s}_boot{b}.png")

    scv.tl.paga(data, groups='induct')
    scv.pl.paga(data, basis = "umap", palette=(col1,col2), save=f"UMAP_paga_{g}_{n}_{s}_boot{b}.png")

    scv.tl.velocity_pseudotime(data)
    cr.tl.lineages(data)
    cr.pl.lineages(data, save=f'lineage_{g}_{n}_{s}_boot{b}.png')

    cr.pl.lineages(data, same_plot=False, save=f'lineage_{g}_{n}_{s}_boot{b}.png')

    drivers = cr.tl.lineage_drivers(data)
    drivers.to_csv(f'all_drivers_{g}_boot{b}.csv')
    #cr.pl.lineage_drivers(data, lineage=pid, n_genes=20, save=f"{pid}_drivers_boot{b}.pdf")
```

### Without Bootstraps
```{python}

g = 'HM'
genes = HM

ntop = (50,75,100,125,150,175,200)
shared = (25,50,75,100)

os.chdir(f'/mnt/Commun/sc_Induction/{pid}/SCENT/{g}/Without_boot')
os.getcwd()

id1 = "Control"
id2 = pid
col1 = "grey"
col2 = "#339900"

for n in ntop:
    for s in shared:
        print("ntop=", n)
        print("shared=", s)
        os.chdir(f'/mnt/Commun/sc_Induction/{pid}/SCENT/{g}/Without_boot/')
        os.getcwd()

        both = Ctrl_filtered.concatenate(Act_filtered)


        D1D2 = []
        for i in both.obs_names :
            i = i.replace(f'{id1}-0', f'{id1}')
            i = i.replace(f'{id2}-1', f'{id2}')
            D1D2.append(i)
        both.obs_names = D1D2

        both.obs["induct"] = np.repeat([id1,id2], [Ctrl_filtered.shape[0], Act_filtered.shape[0]], axis=0)
        scv.pp.filter_and_normalize(both, min_shared_counts=s, n_top_genes=n)

        data = both

        scv.pp.moments(data)
        scv.tl.umap(data, min_dist=1)
        scv.plotting.umap(data, color="induct",palette=(col1, col2), save=f"UMAP_{g}_{n}_{s}.png")

        scv.tl.velocity(data)
        scv.pp.neighbors(data)
        scv.tl.velocity_graph(data)
        scv.pl.velocity_embedding_stream(data , basis='umap', color='induct',palette=(col1, col2), save=f"Velocity_{g}_{n}_{s}.png")

        scv.tl.paga(data, groups='induct')
        scv.pl.paga(data, basis = "umap", palette=(col1, col2),  save = f"UMAP_paga_{g}_{n}_{s}.png")

        pseudo_time = scv.tl.velocity_pseudotime(data)
        scv.pl.scatter(data, color='velocity_pseudotime', color_map='gnuplot', save = f'Pseudotime_ntop{n}_shared{s}_{g}.pdf')
        Pseudotime_value = pd.DataFrame(data.obs['velocity_pseudotime'])
        Pseudotime_value.to_csv(f'Pseudotimes_{g}_{n}_{s}.csv')
        
```


### Import bootstraps

```{r}

Boots = list()
Boot = paste('boot', seq(1:20), sep='')

for (b in 1:20){
   Boots[[b]] = read.csv(sprintf('/mnt/Commun/sc_Induction/%s/SCENT/Bootstraps/boot%i_%s_Ctrl.csv',pid,  b, pid))[,2]
}

```

### Best Paramaters

```{r}

Best_Param = function(g, ntop, shared, id1, id2, col1, col2){
   All_param = list()

   for( b in 1:length(Boot)){
      boots = c()
      parametre = Wstat = pvalue = c()
      pdf(sprintf('/mnt/Commun/sc_Induction/%s/SCENT/%s/Distribution_PseudoT.pdf', pid, g))

      for (n in ntop){
         for (s in shared){
            print(c(n, s))
            PseudoT = read.csv(sprintf('/mnt/Commun/sc_Induction/%s/SCENT/%s/boot%i/Pseudotimes_%s_%i_%i.csv', pid, g, b, g, n, s ))
            PseudoT_ctrl = PseudoT[grep(id1, PseudoT$X),]
            PseudoT_act = PseudoT[grep(id2, PseudoT$X),]
            par(mfrow = c(2,1))
            hist(PseudoT_ctrl$velocity_pseudotime, xlim =c(0,1), breaks = 100, col=col1, xlab = '', main= sprintf('Pseudotimes (%s) [%i_%i]', id1, n, s))
            abline(v=mean(PseudoT_ctrl$velocity_pseudotime), col = 'red',lwd=2)
            hist(PseudoT_act$velocity_pseudotime, xlim =c(0,1), breaks = 100, col=col2, main=sprintf('Pseudotimes (%s) [%i_%i]', id2, n, s), xlab='')
            abline(v=mean(PseudoT_act$velocity_pseudotime), col = 'red',lwd=2)

            Wstat = c(Wstat, as.vector(wilcox.test(PseudoT_act$velocity_pseudotime, PseudoT_ctrl$velocity_pseudotime)$statistic))

            pvalue = c(pvalue, as.vector(wilcox.test(PseudoT_ctrl$velocity_pseudotime, PseudoT_act$velocity_pseudotime)$p.value))
            parametre = c(parametre, paste(n, s, sep='_'))
            boots = c(boots, Boot[b])
         }
      }

      pseudoT_Wilcox = data.frame(Bootstraps = boots, Parametres = parametre, W_stat = Wstat, p_value= pvalue)
      All_param[[b]] = pseudoT_Wilcox
      dev.off()
   }

   return(ldply(lapply(All_param, function(w) as.data.frame(w)), rbind))
}
```

```{r, include = FALSE, echo = FALSE}
id1 = 'Control' #Control
id2 = pid
G = 'HMGO'
ntop = c(50, 75, 100, 125, 150, 175, 200)
shared = c(25,50,75,100)

setwd(sprintf('/mnt/Commun/sc_Induction/%s/SCENT/%s',pid,  G))

param = Best_Param(G, ntop, shared, id1, id2, 'grey', color)
write.csv(param, 'All_param_W.csv')

param = read.csv(sprintf('/mnt/Commun/sc_Induction/%s/SCENT/%s/All_param_W.csv', pid, G))

Comb_parameters = unique(param$Parametres)

W_l = list()

for (b in 1:length(Boot)){
   W = c()
   print(sprintf('Bootstrap %s', b))
   for (i in 1:length(Comb_parameters)){
      p = Comb_parameters[i]
      print(p)
      par = max(param[which(param$Parametres == p),][b,'W_stat'])
      W = c(W,par)
   }
   W_l[[b]] = W
}
names(W_l) = Boot

IDx_max_Wtot = lapply(W_l, function(x) which(x == max(x))[1])

Best_param_per_boot = Comb_parameters[unlist(IDx_max_Wtot)]

setwd(sprintf('/mnt/Commun/sc_Induction/%s/SCENT/%s/',pid, G))
write.csv(Best_param_per_boot, 'Best_param_per_boot.csv')

```

### AUCell Prediction : Meth 1
From whole geneSets

```{r}
Tirosh = read.csv('/mnt/Commun/sc_Induction/scrnaseq_230628/Donnees/Tirosh_MP_genes.csv')
EMT1 = Tirosh[,"MP12.EMT.I"]
EMT2 = Tirosh[,"MP13.EMT.II"]
EMT3 = Tirosh[,"MP14.EMT.III"]
EMT4 = Tirosh[,"MP15.EMT.IV"]
```

```{r, include=FALSE,echo=FALSE}
Boot = paste('Boot', seq(1:20), sep='')
s_AUCell = c(0.05, 0.1, 0.15, 0.2)
ncores = 8
FCTHRESHOLD <- log2(1.5)
seuil_FDR <- 0.05

seuil_AUCell = list()
all_seuil_AUCell = list()


gset_ID_v = c('HM', 'GO', 'HMGO', 'Drivers_HM', 'Drivers_GO', 'Drivers_HMGO', "Tirosh_EMT1", "Tirosh_EMT2", "Tirosh_EMT3", "Tirosh_EMT4")

for (id in 1:length(gset_ID_v)){
   gset_ID = gset_ID_v[id]
   print(gset_ID)
   
   for (s in 1 : length(s_AUCell)){
      aucell.v <- c()
      
      for (b in 1:length(Boot)){
         print(sprintf("Bootstrap randomisation: n=%d", b))

         if (gset_ID == 'HM'){
            gset = HM
         }
         if (gset_ID == 'spls'){
            gset = spls_act_EMT
         }
         
         if (gset_ID == 'GO') {
            gset = GO
         }

         if (gset_ID == 'HMGO'){
            gset = unique(c(HM, GO))
         }
         
         if (gset_ID == "Tirosh_EMT1"){
            gset = EMT1
         }
         if (gset_ID == "Tirosh_EMT2"){
            gset = EMT2
         }
         if (gset_ID == "Tirosh_EMT3"){
            gset = EMT3
         }
         if (gset_ID == "Tirosh_EMT4"){
            gset = EMT4
         }
         if (gset_ID == 'Drivers_HM'){
            file = read.csv(sprintf('/mnt/Commun/sc_Induction/%s/SCENT/HM/all_drivers_HM_boot%i.csv',pid, b-1))#[,"Gene"]
            if (sprintf("%s_2.corr", pid) %in% colnames(file)){
               colnames(file)[which(colnames(file) == sprintf("%s_2.corr", pid))] = sprintf('%s.corr', pid)
            }
            if (sprintf("%s_2.qval", pid) %in% colnames(file)){
               colnames(file)[which(colnames(file) == sprintf("%s_2.qval", pid))] = sprintf('%s.qval', pid)
            }
            gset = file[which(file[,sprintf('%s.qval', pid)] < 0.05 & file[,sprintf('%s.corr', pid)] >0),"Gene"]
         }
      
         if (gset_ID == 'Drivers_GO'){
            file = read.csv(sprintf('/mnt/Commun/sc_Induction/%s/SCENT/GO/all_drivers_GO_boot%i.csv',pid, b-1))#[,"Gene"]
            if (sprintf("%s_2.corr", pid) %in% colnames(file)){
               colnames(file)[which(colnames(file) == sprintf("%s_2.corr", pid))] = sprintf('%s.corr', pid)
            }
            if (sprintf("%s_2.qval", pid) %in% colnames(file)){
               colnames(file)[which(colnames(file) == sprintf("%s_2.qval", pid))] = sprintf('%s.qval', pid)
            }
            gset = file[which(file[,sprintf('%s.qval', pid)] < 0.05 & file[,sprintf('%s.corr', pid)] >0),"Gene"]
         }
      
         if (gset_ID == 'Drivers_HMGO'){
            file = read.csv(sprintf('/mnt/Commun/sc_Induction/%s/SCENT/HMGO/all_drivers_HMGO_boot%i.csv',pid, b-1))#[,"Gene"]
            if (sprintf("%s_2.corr", pid) %in% colnames(file)){
               colnames(file)[which(colnames(file) == sprintf("%s_2.corr", pid))] = sprintf('%s.corr', pid)
            }
            if (sprintf("%s_2.qval", pid) %in% colnames(file)){
               colnames(file)[which(colnames(file) == sprintf("%s_2.qval", pid))] = sprintf('%s.qval', pid)
            }
            gset = file[which(file[,sprintf('%s.qval', pid)] < 0.05 & file[,sprintf('%s.corr', pid)] >0),"Gene"]
         }
         
         subcells = Boots[[b]]

         subcells = gsub('Control', 'inactiv', subcells)
         subcells = gsub(pid, 'activ', subcells)

         subcells = which(colnames(both) %in% subcells)

         discov <- both[,subcells]
         valid <- both[,-subcells]
         dactiv <- isActiv[subcells]
         vactiv <- isActiv[-subcells]
   
         # AUCell GSEA score
         geneSets[[activity]]@geneIds <- gset
         gs <- geneSets[[activity]]
         score = Score_AUCell(as.matrix(valid[,]), gs, s_AUCell[s])
         names(score) <- colnames(valid)
         
         vdat=data.frame(isActiv=vactiv, Score=score)
         aucell.roc=roc(isActiv ~ Score, data=vdat, levels=c("0", "1"))
         aucell.v <- c(aucell.v, auc(aucell.roc))
      }
      seuil_AUCell[[s]] = aucell.v
   }
names(seuil_AUCell) = s_AUCell
all_seuil_AUCell[[id]] = seuil_AUCell
}
names(all_seuil_AUCell) = gset_ID_v

setwd(sprintf('/mnt/Commun/sc_Induction/%s/', pid))

#pdf(sprintf('All_seuil_AUCell_from_%s.pdf',pid))
boxplot(all_seuil_AUCell$HM, ylim = c(0.5,1), ylab = "HM", xlab = 'seuil AUCell')

means <- sapply(all_seuil_AUCell$HM, mean)
for (i in 1:length(means)) {
  text(x = i, y = means[i] + 0.025, labels = round(means[i], 3), cex = 0.8)
}

boxplot(all_seuil_AUCell$GO, ylim = c(0.5,1), ylab = "GO", xlab = 'seuil AUCell')
means <- sapply(all_seuil_AUCell$GO, mean)
for (i in 1:length(means)) {
  text(x = i, y = means[i] + 0.025, labels = round(means[i], 3), cex = 0.8)
}

boxplot(all_seuil_AUCell$HMGO, ylim = c(0.5,1), ylab = "HMGO", xlab = 'seuil AUCell')
means <- sapply(all_seuil_AUCell$HMGO, mean)
for (i in 1:length(means)) {
  text(x = i, y = means[i] + 0.025, labels = round(means[i], 3), cex = 0.8)
}

boxplot(all_seuil_AUCell$Drivers_HM, ylim = c(0.5,1), ylab = "Drivers HM", xlab = 'seuil AUCell')
means <- sapply(all_seuil_AUCell$Drivers_HM, mean)
for (i in 1:length(means)) {
  text(x = i, y = means[i] + 0.025, labels = round(means[i], 3), cex = 0.8)
}

boxplot(all_seuil_AUCell$Drivers_GO, ylim = c(0.5,1), ylab = "Drivers GO", xlab = 'seuil AUCell')
means <- sapply(all_seuil_AUCell$Drivers_GO, mean)
for (i in 1:length(means)) {
  text(x = i, y = means[i] + 0.025, labels = round(means[i], 3), cex = 0.8)
}

boxplot(all_seuil_AUCell$Drivers_HMGO, ylim = c(0.5,1), ylab = "Drivers HMGO", xlab = 'seuil AUCell')
means <- sapply(all_seuil_AUCell$Drivers_HMGO, mean)
for (i in 1:length(means)) {
  text(x = i, y = means[i] + 0.025, labels = round(means[i], 3), cex = 0.8)
}

boxplot(all_seuil_AUCell$Tirosh_EMT1, ylim = c(0.5,1), ylab = "Tirosh EMT1", xlab = 'seuil AUCell')
means <- sapply(all_seuil_AUCell$Tirosh_EMT1, mean)
for (i in 1:length(means)) {
  text(x = i, y = means[i] + 0.025, labels = round(means[i], 3), cex = 0.8, xlab = 'seuil AUCell')
}

boxplot(all_seuil_AUCell$Tirosh_EMT2, ylim = c(0.5,1), ylab = "Tirosh EMT2", xlab = 'seuil AUCell')
means <- sapply(all_seuil_AUCell$Tirosh_EMT2, mean)
for (i in 1:length(means)) {
  text(x = i, y = means[i] + 0.025, labels = round(means[i], 3), cex = 0.8)
}

boxplot(all_seuil_AUCell$Tirosh_EMT3, ylim = c(0.5,1), ylab = "Tirosh EMT3", xlab = 'seuil AUCell')
means <- sapply(all_seuil_AUCell$Tirosh_EMT3, mean)
for (i in 1:length(means)) {
  text(x = i, y = means[i] + 0.025, labels = round(means[i], 3), cex = 0.8)
}

boxplot(all_seuil_AUCell$Tirosh_EMT4, ylim = c(0.5,1), ylab = "Tirosh EMT4", xlab = 'seuil AUCell')
means <- sapply(all_seuil_AUCell$Tirosh_EMT4, mean)
for (i in 1:length(means)) {
  text(x = i, y = means[i] + 0.025, labels = round(means[i], 3), cex = 0.8)
}

dev.off()

saveRDS(all_seuil_AUCell, 'all_seuil_AUCell.Rds')
# HM$`0.2` mean = 0.9576232
# Drivers_HM$`0.2` mean = 0.9779322
# Tirosh_EMT1$`0.2` mean = 0.9138856
# $Tirosh_EMT2$`0.2` 0.9847318
# Tirosh_EMT3$`0.2` 0.7763425
# Tirosh_EMT4$`0.2` mean= 0.8273545
# $GO$`0.2`mean = 0.6103889
# HMGO $HMGO$`0.2`mean = 0.9346519


```

#######################################
#      Pseudotime on all cells        #
#######################################

# Ici, resultats pas terrible, figure pseudotemps ne coincident pas avec UMAP.... de plus, UMAP pas tres bien séparé.
```{r}
ntop = c(50,75,100,125,150, 175, 200)
shared = c(25,50,75,100)
# 
g = 'EMT2'
genes = EMT2
```

# Best param on all cells 

```{r}
parametre = Wstat = pvalue = c()
#pdf(sprintf('/mnt/Commun/sc_Induction/%s/SCENT/%s/Distribution_PseudoT_from_allCells.pdf', pid, g))

for (n in ntop){
   for (s in shared){
      print(c(n, s))
      PseudoT = read.csv(sprintf('/mnt/Commun/sc_Induction/%s/SCENT/%s/Without_boot/Pseudotimes_%s_%i_%i.csv', pid, g, g, n, s ))
      PseudoT_ctrl = PseudoT[grep("Control", PseudoT$X),]
      PseudoT_act = PseudoT[grep(pid, PseudoT$X),]
      par(mfrow = c(2,1))
      hist(PseudoT_ctrl$velocity_pseudotime, xlim =c(0,1), breaks = 100, col='grey', xlab = '', main= sprintf('Pseudotimes (%s) [%i_%i]', 'Control', n, s))
      abline(v=mean(PseudoT_ctrl$velocity_pseudotime), col = 'red',lwd=2)
      hist(PseudoT_act$velocity_pseudotime, xlim =c(0,1), breaks = 100, col=color, main=sprintf('Pseudotimes (%s) [%i_%i]', pid, n, s), xlab='')
      abline(v=mean(PseudoT_act$velocity_pseudotime), col = 'red',lwd=2)

      Wstat = c(Wstat, as.vector(wilcox.test(PseudoT_act$velocity_pseudotime, PseudoT_ctrl$velocity_pseudotime)$statistic))

      pvalue = c(pvalue, as.vector(wilcox.test(PseudoT_ctrl$velocity_pseudotime, PseudoT_act$velocity_pseudotime)$p.value))
      parametre = c(parametre, paste(n, s, sep='_'))
   }
}

param = data.frame(Parametres = parametre, W_stat = Wstat, p_value= pvalue)

Best_param = param[which(param$W_stat == max(param$W_stat)),1]#[1] #75_25


pseudotimes = read.csv(sprintf('/mnt/Commun/sc_Induction/%s/SCENT/%s/Without_boot/Pseudotimes_%s_%s.csv', pid, g, g, Best_param ))
```


